- file:
    path: "{{ nginx_conf.conf_dir }}"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/conf.d"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/conf.mail.d"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/conf.stream.d"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.run_dir }}"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.log_dir }}"
    state: directory
    owner: "{{ nginx_conf.daemon_user }}"
    group: "{{ nginx_settings.log_group }}"
    mode: "{{ nginx_settings.log_mode }}"

- file:
    path: "{{ nginx_conf.http.client_body_temp_path }}"
    state: directory
    owner: "{{ nginx_conf.daemon_user }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.http.proxy_temp_path }}"
    state: directory
    owner: "{{ nginx_conf.daemon_user }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/sites-available"
    state: directory
    owner: "{{ nginx_settings.sites_available_owner }}"
    group: "{{ nginx_settings.sites_available_group }}"
    mode: "{{ nginx_settings.sites_available_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/sites-enabled"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/streams-available"
    state: directory
    owner: "{{ nginx_settings.sites_available_owner }}"
    group: "{{ nginx_settings.sites_available_group }}"
    mode: "{{ nginx_settings.sites_available_mode }}"

- file:
    path: "{{ nginx_conf.conf_dir }}/streams-enabled"
    state: directory
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_dir_mode }}"

- template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "{{ nginx_conf.conf_dir }}/nginx.conf"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_file_mode }}"
  notify:
    - restart nginx
