---

- name: merge vars from files
  merge_yaml_files:
    files:
      - "{{ role_path }}/defaults/main.yml"
      - "{{ role_path }}/vars/{{ ansible_os_family|lower }}.yml"
  delegate_to: 127.0.0.1
  become: no
  register: merged_config

- include_vars:
    file: "{{ merged_config.meta }}"

- set_fact:
    nginx:
      settings: "{{ _nginx_settings|combine(config.nginx.settings) }}"

- include: package.yml
  static: no

- include: config.yml
  static: no

- include: service.yml
  static: no

- include: resource/upstream.yml
  loop_control:
    loop_var: loop_upstream
  vars:
    nginx_upstream: "{{ loop_upstream }}"
  with_items: "{{ config.nginx.upstream|d([]) }}"

- package:
    name: ssl-cert
    state: present

- set_fact:
    nginx_servers: "{{ [_nginx_default_server]|list_append(config.nginx.server) }}"
  when: nginx.settings.default_server|int == 1

- set_fact:
    nginx_servers: "{{ config.nginx.server }}"
  when: nginx.settings.default_server|int != 1

- set_fact:
    server_names: "{{ (server_names|d([])) | list_append('%03d'|format(index|int) ~ '-' ~ server_name|replace(' ', '_') ~ '.conf') }}"
  loop_control:
    loop_var: loop_server_purge
  vars:
    index: "{{ loop_server_purge.0 }}"
    server_name: "{{ loop_server_purge.1 }}"
  with_indexed_items: "{{ (nginx_servers|d([]))|json_query('[].server_name[0]') }}"

- purge_dir:
    dir: "{{ nginx.settings.conf_dir }}/sites-available"
    keep: "{{ server_names|d([]) }}"

- purge_dir:
    dir: "{{ nginx.settings.conf_dir }}/sites-enabled"
    keep: "{{ server_names|d([]) }}"
  notify:
    - restart nginx

- include: resource/server.yml
  loop_control:
    loop_var: loop_server
  vars:
    index: "{{ loop_server.0 }}"
    nginx_server: "{{ loop_server.1 }}"
  with_indexed_items: "{{ nginx_servers|d([]) }}"

- copy:
    src: "{{ role_path }}/files/webserver_landing.html"
    dest: "{{ _nginx_default_server.root }}/index.html"
    owner: "{{ nginx.settings.global_owner }}"
    group: "{{ nginx.settings.global_group }}"
    mode: "{{ nginx.settings.global_file_mode }}"
  when: nginx.settings.default_server|int == 1
  changed_when: False
