---

- include_vars: "{{ ansible_os_family|lower }}.yml"

- set_fact:
    nginx_conf_:
      events: "{{ _nginx_conf_events|combine((_nginx_user_settings.conf|d({})).events|d({})) }}"
      http: "{{ _nginx_conf_http|combine((_nginx_user_settings.conf|d({})).http|d({})) }}"

- set_fact:
    nginx_conf: "{{ _nginx_conf|combine(_nginx_user_settings.conf|d({}), nginx_conf_) }}"
    nginx_geo: "{{ _nginx_user_settings.geo|d([]) }}"
    nginx_map: "{{ _nginx_user_settings.map|d([]) }}"
    nginx_server: "{{ _nginx_user_settings.server|d([]) }}"
    nginx_settings: "{{ (_nginx_user_settings.settings|d({}))|combine(_nginx_settings) }}"
    nginx_upstream: "{{ _nginx_user_settings.upstream|d([]) }}"
    keep_conf_geo: []
    keep_conf_map: []
    keep_conf_server: []
    keep_conf_upstream_http: []
    keep_conf_upstream_stream: []
    keep_server_names: []

- set_fact:
    nginx_server: "{{ [_nginx_default_server]|list_append(nginx_server) }}"
  when: nginx_settings.default_server|int == 1

- include_tasks: package.yml
  static: no

- include_tasks: config.yml
  static: no

- include_tasks: resource/upstream.yml
  loop_control:
    loop_var: loop_upstream
  vars:
    v_upstream: "{{ loop_upstream }}"
  with_items: "{{ nginx_upstream }}"

- include_tasks: resource/server.yml
  loop_control:
    loop_var: loop_server
  vars:
    index: "{{ loop_server.0 }}"
    v_server: "{{ loop_server.1 }}"
  with_indexed_items: "{{ nginx_server }}"

- include_tasks: resource/map.yml
  loop_control:
    loop_var: loop_map
  vars:
    v_map: "{{ loop_map }}"
  with_items: "{{ nginx_map }}"

- include_tasks: resource/geo.yml
  loop_control:
    loop_var: loop_geo
  vars:
    v_geo: "{{ loop_geo }}"
  with_items: "{{ nginx_geo }}"

- copy:
    src: "{{ role_path }}/files/webserver_landing.html"
    dest: "{{ _nginx_default_server.root }}/index.html"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_file_mode }}"
  when: nginx_settings.default_server|int == 1
  changed_when: False

- include_tasks: purge.yml
  static: no

- include_tasks: service.yml
  static: no
