---

- block:
  - service:
      name: "{{ nginx_settings.service_name }}"
      state: "{{ nginx_settings.service_state }}"
      enabled: "{{ nginx_settings.service_enabled }}"

  when: nginx_settings.service_manage
