---

- block:
  - service:
      name: "{{ nginx.settings.service_name }}"
      state: "{{ nginx.settings.service_state }}"
      enabled: "{{ nginx.settings.service_enabled }}"

  when: nginx.settings.service_manage
