---

- set_fact:
    map: "{{ _nginx_map|combine(v_map) }}"

- set_fact:
    keep_conf_map: "{{ keep_conf_map|list_append(map.name ~ '-map.conf') }}"

- template:
    src: "{{ role_path }}/templates/conf.d/map.j2"
    dest: "{{ nginx_conf.conf_dir }}/conf.d/{{ map.name }}-map.conf"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_file_mode }}"
  notify:
    - restart nginx
