---

- set_fact:
    index_formatted: "{{ '%03d'|format(index|int) }}"
    server: "{{ _nginx_server|combine(v_server) }}"

- set_fact:
    sanitized_name: "{{ server.server_name[0]|replace(' ', '_') }}"

- set_fact:
    server_conf_file: "{{ index_formatted }}-{{ sanitized_name }}.conf"

- set_fact:
    keep_conf_server: "{{ keep_conf_server|list_append(server_conf_file) }}"

- include_role:
    name: jtreminio.common
    tasks_from: firewall_add
  loop_control:
    loop_var: loop_rule
  vars:
    rule:
      protocol: tcp
      port: "{{ loop_rule|regex_replace('[A-Za-z]+[0-9]*')|regex_replace('[\\s*]')|regex_replace('[^\\d ]') }}"
      action: accept
  with_items: "{{ server.listen }}"
  when: __jtreminio_manage_firewall

- template:
    src: "{{ role_path }}/templates/server.j2"
    dest: "{{ nginx_settings.conf_dir }}/sites-available/{{ server_conf_file }}"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_file_mode }}"
  notify:
    - restart nginx

- file:
    src: "{{ nginx_settings.conf_dir }}/sites-available/{{ server_conf_file }}"
    dest: "{{ nginx_settings.conf_dir }}/sites-enabled/{{ server_conf_file }}"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    state: link
  notify:
    - restart nginx

- include: geo.yml
  loop_control:
    loop_var: loop_geo
  vars:
    v_geo: "{{ loop_geo }}"
  with_items: "{{ server.geo }}"

- include: map.yml
  loop_control:
    loop_var: loop_map
  vars:
    v_map: "{{ loop_map }}"
  with_items: "{{ server.map }}"
