---

- set_fact:
    upstream: "{{ _nginx_upstream|combine(v_upstream) }}"

- set_fact:
    keep_conf_upstream_http: "{{ keep_conf_upstream_http|list_append(upstream.name ~ '-upstream.conf') }}"
    conf_dir: 'conf.d'
  when: upstream.context == 'http'

- set_fact:
    keep_conf_upstream_stream: "{{ keep_conf_upstream_stream|list_append(upstream.name ~ '-upstream.conf') }}"
    conf_dir: 'conf.stream.d'
  when: upstream.context == 'stream'

- template:
    src: "{{ role_path }}/templates/conf.d/upstream.conf.j2"
    dest: "{{ nginx_settings.conf_dir }}/{{ conf_dir }}/{{ upstream.name }}-upstream.conf"
    owner: "{{ nginx_settings.global_owner }}"
    group: "{{ nginx_settings.global_group }}"
    mode: "{{ nginx_settings.global_file_mode }}"
  notify:
    - restart nginx
