---

- block:
  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62

  - apt_repository:
      repo: "deb https://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    when: nginx.settings.package_source in ('nginx', 'nginx-stable')

  - apt_repository:
      repo: "deb https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    when: nginx.settings.package_source == 'nginx-mainline'

  - block:
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: 16378A33A6EF16762922526E561F9B9CAC40B2F7

    - apt_repository:
        repo: "deb https://oss-binaries.phusionpassenger.com/apt/passenger/ {{ ansible_distribution_release }} main"

    - package:
        name: "{{ item }}"
        state: present
      with_items: ['apt-transport-https', 'ca-certificates']

    - package:
        name: passenger
        state: "{{ nginx.settings.passenger_package_state }}"

    - fail:
        msg: "You must set nginx.settings.package_name to 'nginx-extras' to enable Passenger"
      when: nginx.settings.package_name != 'nginx-extras'

    when: nginx.settings.package_source == 'passenger'

  when: nginx.settings.manage_repo|int == 1

- fail:
    msg: "nginx.settings.package_source must be 'nginx', 'nginx-stable', 'nginx-mainline' or 'passenger'. It was set to '{{ nginx.settings.package_source }}'"
  when: nginx.settings.package_source not in ('nginx', 'nginx-stable', 'nginx-mainline', 'passenger')

- package:
    name: ssl-cert
    state: present

- package:
    name: "{{ nginx.settings.package_name }}"
    state: "{{ nginx.settings.package_state }}"
